apiVersion: v1
kind: Pod
metadata:
  name: pod-victor
  namespace: victor
  labels:
    app: nginx
spec:
  containers:
  - name: quelpoke-victor
    image: europe-west9-docker.pkg.dev/infal-devops-sysops/student-victor/my-app
    ports:
    - containerPort: 8080
    resources:
      requests:
        memory: "64Mi"
        cpu: "50m"
