apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-victor
  namespace: victor
  labels:
    app: quelpoke
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/victor: quelpoke
  template:
    metadata:
      labels:
        app.kubernetes.io/victor: quelpoke
    spec:
      containers:
      - name: quelpoke-victor
        image: europe-west9-docker.pkg.dev/infal-devops-sysops/student-victor/my-app:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
        env:
        - name: Version
          value: victor

---
apiVersion: v1
kind: Service
metadata:
  name: cluster-ip-victor
  namespace: victor
  annotations:
    cloud.google.com/neg: '{"exposed_ports": {"80":{"name": "cluster-ip-victor"}}}'
spec:
  selector:
    app.kubernetes.io/victor: quelpoke
  ports:
    - name:
      protocol: TCP
      port: 80
      targetPort: 8080

---
kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1
metadata:
  name: http-victor
  namespace: victor
spec:
  parentRefs:
  - kind: Gateway
    name: external-http-gateway
    namespace: infra
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /victor
    backendRefs:
    - name: cluster-ip-victor
      port: 80

