name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
    -
        name: Configure Docker to use the GCP credentials
        run: |
          echo "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}" | docker login -u _json_key_base64 --password-stdin https://${{ secrets.GCR_HOSTNAME }}
     
    - name: Build the Docker image
      run: |
          docker build -t ${{ secrets.GCR_HOSTNAME }}/${{ secrets.GCP_PROJECT_ID }}/my-app:$GITHUB_SHA .
          docker tag ${{ secrets.GCR_HOSTNAME }}/${{ secrets.GCP_PROJECT_ID }}/my-app:$GITHUB_SHA ${{ secrets.GCR_HOSTNAME }}/${{ secrets.GCP_PROJECT_ID }}/my-app:latest
    - name: Check Docker image size
      id: check_size
      run: |
        IMAGE_SIZE=$(docker image inspect ${{ secrets.GCR_HOSTNAME }}/${{ secrets.GCP_PROJECT_ID }}/my-app:$GITHUB_SHA --format='{{.Size}}')
        IMAGE_SIZE_MB=$(echo "scale=2; $IMAGE_SIZE/1024/1024" | bc)
        echo "Docker image size: $IMAGE_SIZE_MB MB"
        echo "::set-output name=image_size::$IMAGE_SIZE_MB"

    - name: Fail if image size exceeds 12MB
      if: steps.check_size.outputs.image_size > 12
      run: |
        echo "Image size exceeds the limit of 12MB. Failing the job."
        exit 1

    - name: Push the Docker image to GCR
      run: docker push ${{ secrets.GCR_HOSTNAME }}/${{ secrets.GCP_PROJECT_ID }}/my-app:$GITHUB_SHA
  

    - name: Logout from GCR
      run: docker logout https://${{ secrets.GCR_HOSTNAME }}
    - name: Print the commit SHA   
      run: |
        echo "Commit SHA: $GITHUB_SHA"
