name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
      - name: Docker Login
        run: |
          docker login -u _json_key_base64 --password-stdin https://europe-west9-docker.pkg.dev < {{ secrets.DOCKER_KEY_VICTOR }} 
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: user/app:latest
